language: node_js
node_js:
  - "10.15"
dist: xenial
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test
  - npm run build
  - xvfb-run npm run e2e

