sudo: required
dist: trusty
language: node_js
node_js:
- '10.15'
cache:
  directories:
  - node_modules

addons: 
  ssh_known_hosts: ta70.mckay1717.eu
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

before_script:
  - npm install -g generator-ngx-rocket
  - npm install -g angular-cli
  - npm install -g karma

script:
  - npm run lint
  - ng test --watch false --browsers ChromeHeadless
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_acecc800fc30_key -iv $encrypted_acecc800fc30_iv -in deploy_rsa.enc -out ~\/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~\/deploy_rsa
  - ssh-add ~\/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i deploy_rsa -t travis@ta70.mckay1717.eu 'touch start_build_front'


